package user;

/**
 * This enum contains keys specifying the one-line text prompts that can be printed
 * to console during interactions in <code>UserController</code>.
 */
public enum UserPrompts {

    ACTION_PROMPT,
    ADD_FRIEND_PROMPT,
    REMOVE_FRIEND_PROMPT,
    USER_TYPE_PROMPT,
    INVALID_INPUT_ERROR,
    USER_NOT_FOUND_ERROR,
    NO_USERS_OF_TYPE_ERROR,
    ALREADY_FRIENDS_ERROR,
    NOT_FRIENDS_ERROR,
    EMPTY_FRIENDS_LIST_ERROR,
    ADD_YOURSELF_ERROR,
    ATTENDEE_ADD_ORGANIZER_ERROR,
    ADD_FRIEND_SUCCESS,
    REMOVE_FRIEND_SUCCESS,
    UNBAN_NAME_PROMPT,
    BAN_NAME_PROMPT,
    BAN_REASON_PROMPT,
    BAN_SUCCESS,
    UNBAN_SUCCESS,
    CANNOT_BAN_ERROR,
    DELETE_NAME_PROMPT,
    DELETE_SUCCESS,
    DELETE_UNSUCCESSFUL,
    CHANGE_TYPE_PROMPT,
    CUR_TYPE_ERROR,
    TYPE_CHANGE_PROMPT,
    NEW_TYPE_ERROR,
    ALREADY_TYPE_ERROR,
    TYPE_CHANGE_SUCCESS
}
