package messaging.presenter;

/**
 * This enum contains keys specifying the one-line text prompts
 * that can be printed to console during interactions in <code>MessageController</code>.
 */
public enum MessagePrompts {

    INBOX_TITLE,
    ARCHIVED_TITLE,
    END_OF_INBOX,
    END_OF_ARCHIVES,
    INBOX_MENU_TITLE,
    INBOX_QUIT_PROMPT,
    MESSAGE_INTERACTION_PROMPT,
    INVALID_COMMAND_ERROR,
    MESSAGE_INTERACTION_TITLE,
    MESSAGE_REPLY_PROMPT,
    MESSAGE_DELETE_PROMPT,
    MESSAGE_ARCHIVE_PROMPT,
    MESSAGE_MARK_UNREAD_PROMPT,
    MESSAGE_REMOVE_UNREAD_PROMPT,
    RECIPIENTS_INPUT_PROMPT,
    SINGLE_RECIPIENT_INPUT_PROMPT,
    TEXT_INPUT_PROMPT,
    MESSAGE_CONFIRMATION,
    REPLY_CONFIRMATION,
    DELETION_CONFIRMATION,
    ARCHIVED_CONFIRMATION,
    MARK_UNREAD_CONFIRMATION,
    REMOVE_UNREAD_CONFIRMATION,
    MESSAGE_SELECTION_PROMPT,
    MESSAGE_SELECTION_CANCELLED,
    EMPTY_INBOX_ERROR,
    EMPTY_ARCHIVES_ERROR,
    NO_RECIPIENTS_ERROR,
    INVALID_MESSAGE_SELECTION_ERROR

}
